---
- name: Download SAP software to fileserver
  hosts: fileserver
  become: true
  # collections:
  #   - community.sap_launchpad

  ### This playbook downloads all the SAP files required for installing
  ### SAP HANA and S/4 HANA from Maintenance Planner
  ### This script requires the following variables as input
  #
  # required:
  #   suser_id                 : SAP Credentials required for download
  #   suser_password
  #
  # optional:
  #   download_path           : Pfad in den die Software heruntergeladen wird
  #   venv                     : virtuelles Python environment für prereqs
  #
  # vars_prompt:
  #  - name: "suser_id"
  #    prompt: "S-User ID"
  #    private: false
  #    default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_USERNAME')}}"
  #  - name: "suser_password"
  #    prompt: "S-User PW"
  #    private: true
  #    default: "{{lookup('env', 'SAP_SUPPORT_DOWNLOAD_PASSWORD')}}"

  vars:
    download_path: /sap-software
    sap_hana_sps_version: '06'
    sap_s4_version: '2021'
    sap_software_download_suser_id: "{{ suser_id }}"
    sap_software_download_suser_password: "{{ suser_password }}"
    sap_software_download_find_alternatives: true
    sap_software_download_use_venv: true # should be installed in EE
    sap_software_download_deduplicate: first

  vars_files: "sap-dl-{{ ansible_architecture }}.yml"

  tasks:
    - name: Ensure S-USER and PASSWORD are defined
      ansible.builtin.fail:
        msg: "Please set suser_id and suser_password"
      when: (sap_software_download_suser_id | trim == '') or (sap_software_download_suser_password | trim == '')
      tags:
        - sap_s4_softwaredownload
        - sap_extra_download

    # If this task throws an error, the filelists are not defined
    - name: Define HANA download files
      ansible.builtin.set_fact:
        hana_files: "{{ lookup('vars', 'hdb2sps' + sap_hana_sps_version) }}"
      when:
        - hana_files is undefined

    - name: Define S4 download files
      ansible.builtin.set_fact:
        s4fndn_files: "{{ lookup('vars', 's4fndn' + sap_s4_version) }}"
      when:
        - s4fndn_files is undefined

    - name: Ensure download directories exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ download_path }}"
        - "{{ download_path + '/HANA2SPS' + sap_hana_sps_version }}"
        - "{{ download_path + '/S4HANA' + sap_s4_version + '.FNDN' }}"

    - name: Download SAPCAR
      ansible.builtin.include_role:
        name: community.sap_launchpad.sap_software_download
      vars:
        sap_software_download_directory: "{{ download_path }}"
        sap_software_download_files: "{{ sapcar }}"

    - name: Download Hana Media
      ansible.builtin.include_role:
        name: community.sap_launchpad.sap_software_download
      vars:
        sap_software_download_directory: "{{ download_path + '/HANA2SPS' + sap_hana_sps_version }}"
        sap_software_download_files: "{{ hana_files }}"

    - name: Download S4 Media
      ansible.builtin.include_role:
        name: community.sap_launchpad.sap_software_download
      vars:
        sap_software_download_directory: "{{ download_path }}/S4HANA{{ sap_s4_version }}.FNDN"
        sap_software_download_files: "{{ s4fndn_files + swpm }}"
        sap_software_download_deduplicate: first

    - name: Link SAPCAR
      ansible.builtin.file:
        src: '{{ download_path }}/{{ sapcar | first }}'
        dest: '{{ item }}'
        state: hard
        mode: '755'
      loop:
        - '{{ download_path }}/S4HANA{{ sap_s4_version }}.FNDN/{{ sapcar | first }}'
        - '{{ download_path }}/HANA2SPS{{ sap_hana_sps_version }}/{{ sapcar | first }}'
